//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresa
    {
        public int Id { get; set; }
        public string Strada { get; set; }
        public string Bloc { get; set; }
        public string Localitate { get; set; }
        public Nullable<int> PersonID { get; set; }
    }
}
